# -*- coding: utf-8 -*-
"""Generate requirements/ENG-SOURCING.md from the functional specs.

The SPEC is the source of truth. This index is derived from it, so it cannot
drift: every `Source:` line carrying a Eng marker becomes a row.

Run:  python requirements/tools/gen-eng-sourcing.py
"""
import io, os, re, glob, datetime

HERE = os.path.dirname(os.path.abspath(__file__))
REQ = os.path.dirname(HERE)
SPECS = os.path.join(REQ, 'functional-spec')
OUT = os.path.join(REQ, 'ENG-SOURCING.md')

WARN = u'⚠'
MID = u'·'

SCREEN_TITLES = {}

def clean(s):
    s = s.strip()
    s = re.sub(r'^-\s*', '', s)
    s = re.sub(r'^\*\*Source:\*\*\s*', '', s)
    s = re.sub(r'\s+', ' ', s)
    return s.strip()

def harvest(path):
    """Return (screen_id, screen_title, [(component, entry_text)])."""
    text = io.open(path, encoding='utf-8').read()
    lines = text.split('\n')

    m = re.search(r'^#\s+(.*)$', text, re.M)
    title = m.group(1).strip() if m else os.path.basename(path)
    screen = os.path.basename(path).split('-')[0]

    rows = []
    comp = '(screen level)'
    i = 0
    while i < len(lines):
        L = lines[i]
        h = re.match(r'^###\s+(.*)$', L)
        if h:
            comp = h.group(1).strip()
        if '**Source:**' in L:
            # collect the Source line plus any indented continuation/sub-bullets
            block = [L]
            j = i + 1
            while j < len(lines) and re.match(r'^\s{2,}\S', lines[j]) \
                    and '**Source:**' not in lines[j]:
                block.append(lines[j])
                j += 1
            # split the block into entries: top line, then each "  - " sub-bullet
            entries, cur = [], []
            for b in block:
                if re.match(r'^\s{2,}-\s', b):
                    if cur:
                        entries.append(' '.join(cur))
                    cur = [b]
                else:
                    cur.append(b)
            if cur:
                entries.append(' '.join(cur))
            for e in entries:
                if WARN + ' Eng' in e:
                    rows.append((comp, clean(e)))
            i = j
            continue
        i += 1
    return screen, title, rows


def main():
    blocks = []
    total = 0
    for path in sorted(glob.glob(os.path.join(SPECS, '*.md'))):
        if os.path.basename(path).startswith('_'):
            continue
        screen, title, rows = harvest(path)
        if not rows:
            continue
        total += len(rows)
        blocks.append((screen, title, rows))

    out = []
    w = out.append
    w('# <PRODUCT> — Engineering sourcing index')
    w('')
    w('> **Generated from the functional specs.** Do not edit this file — edit the `Source:` line')
    w('> in the component block it came from and regenerate '
      '(`python requirements/tools/gen-eng-sourcing.py`).')
    w('>')
    w('> **What a row means.** The **behaviour is ruled and buildable**; what is outstanding is the')
    w('> **name of the field and the system that owns it**. None of these is a product question and')
    w('> none should come back to Product. Where a row asks a question, it is a question about the')
    w('> real systems that only Engineering can answer.')
    w('')
    w('Conventions that apply across every row — the clock, currency, nulls, Lines vs Articles,')
    w('article kinds, identifiers, and what must **not** ship — are in **`DATA-CONVENTIONS.md`**.')
    w('')
    w('---')
    w('')
    w('## Every sourcing item, by screen')
    w('')
    w('**%d items across %d screens.**' % (total, len(blocks)))
    w('')

    for screen, title, rows in blocks:
        w('### `%s` — %s' % (screen, re.sub(r'^.*?—\s*', '', title)))
        w('')
        w('| Component | What Engineering needs to supply or confirm |')
        w('|---|---|')
        for comp, entry in rows:
            c = comp.replace('|', '\\|')
            e = entry.replace('|', '\\|')
            w('| %s | %s |' % (c, e))
        w('')

    w('---')
    w('')
    w('## Not a sourcing question')
    w('')
    w('Items marked `%s OPEN` in a spec\'s **§E** are **product or design** decisions with a named' % WARN)
    w('owner, and are tracked there and in `OPEN-ITEMS.md` — not here.')
    w('')
    w('_Generated %s._' % datetime.date.today().isoformat())

    io.open(OUT, 'w', encoding='utf-8', newline='\n').write('\n'.join(out) + '\n')
    print('wrote %s — %d items across %d screens' % (OUT, total, len(blocks)))


if __name__ == '__main__':
    main()
